Update patch set 5
Patch Set 5: Code-Review-1

I see below exception when running scons. Anyt

1. cloned contrail-api-client repo
2. run scons <- works, generated pip installable source dist
3. apply patchset #5
4. run scons, fails with below exception


Traceback (most recent call last):
  File "generateds/generateDS.py", line 2771, in <module>
    main()
  File "generateds/generateDS.py", line 2764, in main
    pgenr.parseAndGenerate()
  File "generateds/generateDS.py", line 1116, in parseAndGenerate
    self._Generator.generate(root, infile, self.outFilename)
  File "/root/contrail-api-client/generateds/ccmap.py", line 222, in generate
    self._GenerateFrontendClassDefinitions(root)
  File "/root/contrail-api-client/generateds/ccmap.py", line 182, in _GenerateFrontendClassDefinitions
    apigen.Generate(self._Parser.outFilename)
  File "/root/contrail-api-client/generateds/ifmap_frontend.py", line 55, in Generate
    self._generate_heat_resources(gen_filepath_pfx, gen_filename_pfx)
  File "/root/contrail-api-client/generateds/ifmap_frontend.py", line 1996, in _generate_heat_resources
    self.res_xsd = importlib.import_module('.resource_xsd', package='vnc_api.gen')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/contrail-api-client/build/debug/api-lib/vnc_api/gen/resource_xsd.py", line 6, in <module>
    from .generatedssuper import *
ImportError: No module named generatedssuper


scons: *** [build/debug/api-lib/vnc_api/gen/__init__.py] Error 1
scons: building terminated because of errors.

Patch-set: 5
Reviewer: Gerrit User 64 <64@c72cd27d-1743-4a55-84a4-cd13b8400c52>
Label: Code-Review=-1