client: remove unecessary log warnings
It may be expected that the function to return None, so that would
indicated that the module is not loaded and we should. That would
avoid the uninformative messages in ours logs like:

  Exception: module 'vnc_cfg_api_server.resources' has no attribute...

Related-Jira-Bug: CEM-14223
Signed-off-by: Sahid Orentino Ferdjaoui <sferdjaoui@juniper.net>
Change-Id: I4eb1c7130bf7de1460905b4a8371ec89350ca098